### PR TITLE
Add automated build process

### PR DESCRIPTION
**Pull request by lunix33**
*https://github.com/tanjo3/tww_apworld/pull/1#issuecomment-1984228877*
> [...] And yeah, I don't have a build script for this; just doing it manually.

*https://github.com/tanjo3/tww_apworld/pull/1#issuecomment-1984241428*
> Would you like me to add a build script for you?

*https://github.com/tanjo3/tww_apworld/pull/1#issuecomment-1984249976*
> Sure, that'd be appreciated. Would this be a GitHub actions workflow? I can commit the sample YAML to the repository.

As previously talked about, what I was thinking is creating a shell script taking care of building the project.

But I was also thinking it might in fact be nice to have a github action in place to do it either on request though the action panel, or based on commits and/or PRs, depending on what you prefer.

And I can make the action yaml file myself unless you want to use a specific template...

# Note

`dolphin-memory engine` can be included using the script included in this comment: https://github.com/tanjo3/tww_apworld/pull/1#issuecomment-1973891777.
Would probably need to simplify it since there's only one dependency so it's kinda overkill.

### CODE REVIEW

**Comment by lunix33** [comment]
I've started looking into building the script.

I've noticed, you've been including the base yaml file in your build, but I don't think I saw it in the repo, am I mistaken, is there a reason why it's missing?

I saw you've been including essentially the whole source code in your release, was there a reason for that? wouldn't it be "simpler" for the user if the `tww` folder wouldn't be present?

I'd like you to tell me what you think of having the license file of `dolphin-memory-engine` directly in its folder. 

Also I've been taking into consideration the requirement file, when bundling the requirements, so I've been putting those in the a `lib` folder to mimic the archipelago installation folder. And that way if you decide to add more libraries they should be processed mostly auto-magically.
By extension, I don't know if it would make sense to put the `tww.apworld` in `lib/worlds`.

Thoughts?

**Comment by tanjo3** [comment]
> I've noticed, you've been including the base yaml file in your build, but I don't think I saw it in the repo, am I mistaken, is there a reason why it's missing?

No reason in particular, that's what I meant when I said I can commit the sample YAML to the repository. I'll just do that.

> I saw you've been including essentially the whole source code in your release, was there a reason for that? wouldn't it be "simpler" for the user if the tww folder wouldn't be present?

Honestly, I've just kinda followed how the BfBB dev did their apworld releases. I think it's nice to have there just so the user can look at the code if they have concerns, but I suppose they could always just unzip the apworld file. If it'd make the build script easier, then feel free to not include it.

> I'd like you to tell me what you think of having the license file of dolphin-memory-engine directly in its folder.

That's probably fine. I'm not familiar with the legalities regarding license files.

> Also I've been taking into consideration the requirement file, when bundling the requirements, so I've been putting those in the a lib folder to mimic the archipelago installation folder. And that way if you decide to add more libraries they should be processed mostly auto-magically.
By extension, I don't know if it would make sense to put the tww.apworld in lib/worlds.

So, the user would just have to, say, drag and drop the lib/ folder in the release onto their AP lib/ folder? That's fine, though it will require an update to the setup guide. To some degree, I like having the apworld at the top level, just for "visibility" in that the user can see immediately that they've downloaded the apworld file. But this "ease-of-installation" is probably for the better.

**Comment by lunix33** [comment]
> No reason in particular, that's what I meant when I said I can commit the sample YAML to the repository. I'll just do that. 

Oh okay, sorry I thought you meant a github action template yaml file. That's my bad.

> [...]  I suppose they could always just unzip the apworld file. If it'd make the build script easier, then feel free to not include it.

When it comes to that, the issue I have isn't about the complexity of the the script, it's mostly that i think it might get inexperienced user confused since there's more stuff in the zip. But also it makes the zip heavier (okay, it's just a few files since the repo isn't huge, but still). Lastly, since it's a production build, I just think it's a bit uncommon to have the source code included with the release build (when speaking about software release in general), and users whom are familiar with archipelago in can in fact just unzip the apworld, they also know where the repo is, so they should also be able to just browse the code on github (or clone it).

But. If you rather still have it, then I'll include it. It won't be hard to add that step to the build, it's 1 line.

> So, the user would just have to, say, drag and drop the lib/ folder in the release onto their AP lib/ folder? That's fine, though it will require an update to the setup guide. To some degree, I like having the apworld at the top level, just for "visibility" in that the user can see immediately that they've downloaded the apworld file. But this "ease-of-installation" is probably for the better.

never mind. I'll just include the apworld at the root since you prefer it, but also directory merging can be a whole can of worm in itself. Not all OS support directory merging, and if they do, it doesn't mean it will do it the way we expect it.
Though I'll still need to modify the setup steps to say they need to copy the content of the `lib` folder into archipelago's lib folder.

**Comment by tanjo3** [comment]
Alright. Yeah, let's go with removing the source code tww/ folder and keeping the apworld at root, then. Thanks.

**Comment by lunix33** [comment]
I think I'm mostly(tm) done with the initial build script. I am able to generate the archive and it seems to be working from what I've tested.

Here's the folder structure I have atm.
```
.
├── lib
│   └── dolphin_memory_engine
│       ├── _dolphin_memory_engine.cp311-win_amd64.pyd
│       ├── _dolphin_memory_engine.cpython-311-x86_64-linux-gnu.so
│       ├── __init__.py
│       ├── LICENSE
│       └── version.py
├── LICENSE.md
├── README.md
├── The Wind Waker.yaml
└── tww.apworld
```
There's still a few things I want to change. But you should be able to start looking into it.

Also I ended up removing the `inc` folder since it's not needed from what I've tested and it's just a duplicate of the code distributed by the pip package, which we shouldn't have to handle imo.

**Comment by tanjo3** [comment]
> Also I ended up removing the `inc` folder since it's not needed from what I've tested and it's just a duplicate of the code distributed by the pip package, which we shouldn't have to handle imo.

~~I'm not sure this works. I built an apworld with this change and it doesn't seem to be working. Although, it's not raising an errors either, for some reason. Is the apworld working for you?~~

Never mind, I'm dumb. I forgot to copy the contents of `dolphin_memory_engine` over to AP. Everything looks good.

**Comment by lunix33** [comment]
Okay, if you want to start looking into the `build.sh` file for review I think you can. I don't think I'll make any more change to it unless the github action stuff gets quirky, but I don't think it will be an issue.

**Comment by lunix33** [comment]
Okay, everything should be good to be reviewed now. The script and the github action are in place.

When it comes to the github action, it should trigger automatically when you create a version tag (eg: v1.2.3[-rc4]), or when you trigger a manual build from the `Action` menu.
I didn't think it made much sense to create a build for each commit or pull request since it would just eat you credits needlessly.

When you create a tag, the action will automatically create a new draft release with the file attached to it. So once the build is done, you can go in the release section to finalize it before publishing.

**Comment by tanjo3** [comment]
Awesome, looked through the code, the script output, and the apworld and it all looks good to me. Very cool stuff! Do you think the installation steps in the setup guide should be modified with the new structure change for the `dolphin-memory-engine` folder (now that it's in `lib/`)?

**Comment by lunix33** [comment]
Oh, yeah! I forgot to change that part.
I'll make the change, then if things looks good to you we should be golden!

**Comment by lunix33** [comment]
The change is applied. Just let me know if there's anything else.

**Comment by tanjo3** [comment]
Looks good, so I'll merge. From next release onward, I'll use the actions for the builds. Thanks again for this! Great work.

I'd like to add you to the credits of the README. How would you prefer to be named?

**Comment by lunix33** [comment]
It was a pleasure to be able to help!

If you want to add me to the README, you can use "Lunix" as my name.
Yeah, I know. You can thank much younger me for that name :p

**Pull request merged**
